# Generated by Django 3.2 on 2021-07-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_form', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
