# Generated by Django 3.2 on 2021-07-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_form', '0004_alter_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='Insert text here'),
        ),
    ]
