# Generated by Django 3.2 on 2021-07-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_form', '0006_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(),
        ),
    ]
