# Generated by Django 3.2 on 2021-04-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
